sudo: false
language: python
python:
  - "2.7"

env:
  - PEBBLE_SDK_VERSION=3.13.1

before_install:
  - wget https://github.com/pebble/pebble-tool/releases/download/v4.4-dp2/pebble-sdk-4.4-dp2-linux64.tar.bz2?source=travis
  - mkdir -p ~/.pebble-sdk
  - tar -jxf pebble-sdk-* -C ~/.pebble-sdk
  - touch ~/.pebble-sdk/ENABLE_ANALYTICS
  - export PEBBLE_SDK=~/.pebble-sdk/pebble-sdk-*
  - export PEBBLE=$PEBBLE_SDK/bin/pebble

install:
  - pushd $PEBBLE_SDK
  - virtualenv --no-site-packages .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - deactivate
  - popd
  - $PEBBLE sdk set-channel beta
  - yes | $PEBBLE sdk install $PEBBLE_SDK_VERSION

script:
  - $PEBBLE build
